### ISSUE TITLE
Test case 02-05 review

### ISSUE THREAD

**Issue by luismateusme** [ArmandDu/shortcut-react-club#2]
I believe that the following solution matches the exercise 02-05. However, some tests fail.
Either it's me or the test case :)
`
export const SocialMedia = props => {
  return (
    <div id="SocialMedia">
      <h1 id="title">{props.title}</h1>
      <div className="so-me container">
        {props.posts.map(post => (
          <Post
            key={post.id}
            author={post.author}
            title={post.title}
            postedOn={post.date}
            liked={post.liked}
            children={<p>{post.content}</p>}
          />
        ))}
      </div>
    </div>
  );
};
`

**Comment by ArmandDu** [comment]
Looking into it
